### ISSUE TITLE
[BUG] Downloaded cases use the wrong text typing sound.

### ISSUE THREAD

**Issue by DeathByAutoscroll** [falko17/aaoffline#1]
Testing using Erinaceinae Griminance, ID: 145513. Downloaded cases incorrectly use the more electronic boop text sound effect instead of the more typewriter-y one.
https://github.com/user-attachments/assets/6cdfc9b3-d768-4dab-ae92-71497b999616

**Comment by falko17** [comment]
Thanks for the report. Interestingly, this seems to only occur in Firefox. I'll try investigating it soon.

**Comment by falko17** [comment]
This seems to be caused by Firefox not handling HTML5 audio the same way as other browsers. We need to use the HTML5 audio API because, if we don't, CORS errors appear when opening the HTML file locally (we're not allowed to access other local files from `index.html` for security reasons) and Howler.js switches to HTML5 audio automatically anyway. 
I'm not completely sure why this difference in browsers exists, but I don't really have the time right now to investigate this that deeply.

Instead, I implemented a work-around in commit ebae401. The only (easy) way around this problem that I'm aware of is to avoid using HTML5 audio, so I added a command-line option `--disable-html5-audio`. Of course, this just brings us back to the issue of CORS errors—to fix *those*, you'll have to run a local web server (e.g., `python3 -m http.server -d $CASE_DIRECTORY`) that serves the files, then `index.html` is allowed to make requests to other local resources. I've added instructions regarding this to the README.md and `--help`.

If I come across any other ideas on how to fix this in the future without requiring this workaround, I'll re-open this issue, but for now, I'll consider this closed. Thanks again for the bug report.
